# -*- coding: utf-8 -*-
"""5.2 - Despliegue - Clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BfLJi2thhJDyOWxjLV4o7FhrihQx80G

# Despliegue
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-class.pkl'
modelo, min_max_scaler, variables, extra = pickle.load(open(filename, 'rb'))

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
st.title('Predicción para ataque de corazón')

age = st.slider('age', min_value=1, max_value=82, value=20, step=1)
avg_glucose_level = st.slider('avg_glucose_level', min_value=55.12, max_value=271.74, value=100.0, step=1.0)
hypertension = st.selectbox('hypertension', ["No",'Yes'])
heart_disease = st.selectbox('heart_disease', ['No', 'Yes'])
ever_married = st.selectbox('ever_married', ['Yes', 'No'])
smoking_status = st.selectbox('smoking_status', ["'never smoked'", "Unknown","'formerly smoked'","smokes"])
stroke_ataque_corazon = st.selectbox('stroke_ataque_corazon', ['No', 'Yes'])

#Dataframe
datos = [[age, avg_glucose_level,hypertension,heart_disease,ever_married, smoking_status, stroke_ataque_corazon]]
data = pd.DataFrame(datos, columns=['age', 'avg_glucose_level','hypertension','heart_disease','ever_married','smoking_status','stroke_ataque_corazon']) #Dataframe con los mismos nombres de variables

# Recordar medida de error del modelo
st.warning("El modelo tiene un error del 11%")
