# -*- coding: utf-8 -*-
"""5.2 - Despliegue - Clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BfLJi2thhJDyOWxjLV4o7FhrihQx80G

# Despliegue
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-class.pkl'
obj = pickle.load(open(filename, 'rb'))
modelo = obj[0]
encoder = obj[1]      # probablemente no lo uses
variables = obj[2]    # columnas correctas
scaler = obj[3]

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
st.title('Predicción para ataque de corazón')

age = st.slider('age', min_value=1, max_value=82, value=20, step=1)
avg_glucose_level = st.slider('avg_glucose_level', min_value=55.12, max_value=271.74, value=100.0, step=1.0)
hypertension = st.selectbox('hypertension', ["No",'Yes'])
heart_disease = st.selectbox('heart_disease', ['No', 'Yes'])
ever_married = st.selectbox('ever_married', ['Yes', 'No'])
smoking_status = st.selectbox('smoking_status', ["'never smoked'", "Unknown","'formerly smoked'","smokes"])

#Dataframe
datos = [[age, avg_glucose_level,hypertension,heart_disease,ever_married, smoking_status]]
data = pd.DataFrame(datos, columns=['age', 'avg_glucose_level','hypertension','heart_disease','ever_married','smoking_status']) #Dataframe con los mismos nombres de variables


if st.button("Predecir"):

    df = pd.DataFrame(0, index=[0], columns=variables)

    # Numéricas
    df['age'] = age
    df['avg_glucose_level'] = avg_glucose_level

    # Binarias
    if hypertension == 'Yes':
        df['hypertension_Yes'] = 1

    if heart_disease == 'Yes':
        df['heart_disease_Yes'] = 1

    if ever_married == 'Yes':
        df['ever_married_Yes'] = 1

    # Smoking (usar EXACTO como está en variables)
    col_smoke = f"smoking_status_{smoking_status}"
    if col_smoke in df.columns:
        df[col_smoke] = 1

    # Escalar
    X_scaled = scaler.transform(df.values)

    # Predecir
    pred = modelo.predict(X_scaled)

    # Resultado
    if pred[0] == 1:
        st.error("⚠️ Alto riesgo de ataque cerebrovascular")
    else:
        st.success("✅ Bajo riesgo")
# Recordar medida de error del modelo
st.warning("El modelo no es 100% seguro")
